In [1]:
%run ../Python_files/create_path-link_incidence_matrix_Sioux.py

In [3]:
np.shape(P)

(552, 14232)

In [9]:
P_dict = {}

assert(np.shape(P)[0] == 552)
assert(np.shape(P)[1] == 14232)

for i in range(np.shape(P)[0]):
    for j in range(np.shape(P)[1]):
        key = str(i+1) + '-' + str(j+1)
        if (P[i, j] != 0):
            P_dict[key] = P[i, j]
        
with open('od_pair_route_incidence_Sioux.json', 'w') as json_file:
    json.dump(P_dict, json_file)

In [10]:
np.shape(A)

(76, 14232)

In [11]:
A_dict = {}

assert(np.shape(A)[0] == 76)
assert(np.shape(A)[1] == 14232)

for i in range(np.shape(A)[0]):
    for j in range(np.shape(A)[1]):
        key = str(i+1) + '-' + str(j+1)
        if (A[i, j] != 0):
            A_dict[key] = A[i, j]
        
with open('link_route_incidence_Sioux.json', 'w') as json_file:
    json.dump(A_dict, json_file)

In [8]:
A_t = np.transpose(A)
P_t = np.transpose(P)
# PA'
AP_t = np.dot(A, P_t)
print("rank of P is: ")
print(matrix_rank(P))
print("sizes of P are: ")
print(np.size(P, 0))
print(np.size(P, 1))
print("rank of A is: ")
print(matrix_rank(A))
print("sizes of A are: ")
print(np.size(A, 0))
print(np.size(A, 1))
print("rank of AP_t is: ")
print(matrix_rank(AP_t))
print("shape of AP_t is: ")
print(np.shape(AP_t))

rank of P is: 
552
sizes of P are: 
552
14232
rank of A is: 
76
sizes of A are: 
76
14232
rank of AP_t is: 
76
shape of AP_t is: 
(76, 552)


In [4]:
pinv_AP_t = np.linalg.pinv(AP_t)

In [6]:
np.shape(pinv_AP_t)

(552, 76)

### Assignment Equation

We have the following equation: 
$$AP'\boldsymbol{\lambda} = \textbf{x},$$
whose least-squares solution can be written as
$$\boldsymbol{\lambda} = (AP')^+\textbf{x},$$
where $(AP')^{+}$ is the pseudo-inverse of $AP'$.

In [6]:
AA = [[1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
      [0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
      [0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0],
      [0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
      [0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0]]

In [7]:
AA = np.array(AA)

In [8]:
AA

array([[1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1],
       [0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0]])

In [9]:
PP = [[0.8, 0.2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0.8, 0.2, 0, 0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0.8, 0.2, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0.8, 0.2, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0.8, 0.2, 0, 0],
      [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.8, 0.2]]

In [10]:
PP = np.array(PP)

In [11]:
PP

array([[ 0.8,  0.2,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ],
       [ 0. ,  0. ,  0.8,  0.2,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0.8,  0.2,  0. ,  0. ,  0. ,  0. ,  0. ,
         0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0.8,  0.2,  0. ,  0. ,  0. ,
         0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0.8,  0.2,  0. ,
         0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0.8,
         0.2]])

In [12]:
AA_t = np.transpose(AA)

In [17]:
PPAA_t = np.dot(PP, AA_t)

In [18]:
AAPP_t = np.transpose(PPAA_t)

In [19]:
AAPP_t

array([[ 0.8,  0.2,  0. ,  0. ,  0. ,  0.2],
       [ 0. ,  0.2,  0.2,  0.8,  0. ,  0. ],
       [ 0. ,  0. ,  0.2,  0. ,  0.8,  0.2],
       [ 0.2,  0.8,  0. ,  0.2,  0. ,  0. ],
       [ 0.2,  0. ,  0. ,  0. ,  0.2,  0.8],
       [ 0. ,  0. ,  0.8,  0.2,  0.2,  0. ]])

In [20]:
lam = [[100], [100], [100], [100], [100], [100]]

In [21]:
lam = np.array(lam)

In [22]:
lam

array([[100],
       [100],
       [100],
       [100],
       [100],
       [100]])

In [23]:
np.dot(AAPP_t, lam)

array([[ 120.],
       [ 120.],
       [ 120.],
       [ 120.],
       [ 120.],
       [ 120.]])