In [1]:
using JSON

#load OD pair-route incidence
odPairRoute = readall("od_pair_route_incidence_Sioux_simp.json");
odPairRoute = JSON.parse(odPairRoute);

#load link-route incidence
linkRoute = readall("link_route_incidence_Sioux_simp.json");
linkRoute = JSON.parse(linkRoute);

#load OD pair labels
odPairLabel = readall("od_pair_label_dict_Sioux_simp_refined.json");
odPairLabel = JSON.parse(odPairLabel);

odPairLabel_ = readall("od_pair_label_dict__Sioux_simp_refined.json");
odPairLabel_ = JSON.parse(odPairLabel_);

#load link labels
linkLabel = readall("link_label_dict_Sioux_simp.json");
linkLabel = JSON.parse(linkLabel);

linkLabel_ = readall("link_label_dict_Sioux_simp_.json");
linkLabel_ = JSON.parse(linkLabel_);

#load node-link incidence
nodeLink = readall("node_link_incidence_Sioux_simp.json");
nodeLink = JSON.parse(nodeLink);

In [2]:
include("load_network_uni-class.jl")

load_ta_network (generic function with 2 methods)

In [3]:
ta_data = load_ta_network("Sioux_simp");

In [4]:
capacity = ta_data.capacity;
free_flow_time = ta_data.free_flow_time;

In [5]:
############
#Read in the demand file
file = open("../data_traffic_assignment_uni-class/SiouxFalls_trips_simp.txt")
demands = Dict{(Int64,Int64), Float64}()
s = 0
for line in eachline(file)
    if contains(line, "Origin")
        s = int(split(line)[2])
    else
        pairs = split(line, ";")
        for pair in pairs
            if !contains(pair, "\n")
                pair_vals = split(pair, ":")
                t, demand = int(pair_vals[1]), float(pair_vals[2])
                demands[(s,t)] = demand 
            end
        end
    end
end                
close(file)

In [6]:
demands

Dict{(Int64,Int64),Float64} with 100 entries:
  (8,10) => 1600.0
  (9,5)  => 800.0
  (3,6)  => 300.0
  (10,5) => 1000.0
  (6,9)  => 400.0
  (4,4)  => 0.0
  (9,4)  => 700.0
  (8,9)  => 800.0
  (9,1)  => 500.0
  (3,1)  => 100.0
  (1,10) => 1300.0
  (4,5)  => 500.0
  (9,9)  => 0.0
  (2,4)  => 200.0
  (6,5)  => 200.0
  (4,9)  => 700.0
  (8,4)  => 700.0
  (1,2)  => 100.0
  (9,2)  => 200.0
  (5,1)  => 200.0
  (9,8)  => 800.0
  (3,4)  => 200.0
  (9,6)  => 400.0
  (10,6) => 800.0
  (8,2)  => 400.0
  ⋮      => ⋮

In [7]:
odPairLabel_

Dict{String,Any} with 90 entries:
  "32" => {4,6}
  "29" => {4,2}
  "81" => {9,10}
  "54" => {6,10}
  "1"  => {1,2}
  "78" => {9,6}
  "2"  => {1,3}
  "74" => {9,2}
  "41" => {5,6}
  "65" => {8,2}
  "51" => {6,7}
  "53" => {6,9}
  "27" => {3,10}
  "75" => {9,3}
  "42" => {5,7}
  "33" => {4,7}
  "28" => {4,1}
  "50" => {6,5}
  "52" => {6,8}
  "63" => {7,10}
  "88" => {10,7}
  "26" => {3,9}
  "10" => {2,1}
  "77" => {9,5}
  "24" => {3,7}
  ⋮    => ⋮

In [8]:
demandsVec = zeros(length(odPairLabel_))

for i = 1:length(demandsVec)
    demandsVec[i] = demands[(odPairLabel_["$i"][1], odPairLabel_["$i"][2])]
end

In [9]:
demandsVec

90-element Array{Float64,1}:
  100.0
  100.0
  500.0
  200.0
  300.0
  500.0
  800.0
  500.0
 1300.0
  100.0
  100.0
  200.0
  100.0
    ⋮  
  600.0
  800.0
 2800.0
 1300.0
  600.0
  300.0
 1200.0
 1000.0
  800.0
 1900.0
 1600.0
 2800.0

In [12]:
for key=keys(odPairRoute)
    if contains(key, "90-")
        println(key)
    end
end

90-294


In [13]:
using JuMP
using Gurobi

# m = Model(solver=GurobiSolver(OutputFlag=false))
m = Model()

numLinks = 22
numRoute = 294
numOD = 90

@defVar(m, linkFlow[1:numLinks])
@defVar(m, pathFlow[1:numRoute])

pathFlowSum = Dict()

for i=1:numOD
    pathFlowSum[i] = 0
    for j=1:numRoute
        if "$(i)-$(j)" in keys(odPairRoute)
            pathFlowSum[i] += pathFlow[j]
        end
    end
    @addConstraint(m, pathFlowSum[i] == demandsVec[i])
end

pathFlowLinkSum = Dict()

for a=1:numLinks
    pathFlowLinkSum[a] = 0
    for j=1:numRoute
        if "$(a)-$(j)" in keys(linkRoute)
            pathFlowLinkSum[a] += pathFlow[j]
        end
    end
    @addConstraint(m, pathFlowLinkSum[a] == linkFlow[a])
end

for j=1:numRoute
    @addConstraint(m, pathFlow[j] >= 0)
end

@defNLExpr(f, sum{free_flow_time[a]*linkFlow[a] + .03*free_flow_time[a]*((linkFlow[a])^5)/((capacity[a])^4), a = 1:numLinks})

@setNLObjective(m, Min, f)

solve(m)

This is Ipopt version 3.12.1, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

Number of nonzeros in equality constraint Jacobian...:     1614
Number of nonzeros in inequality constraint Jacobian.:      294
Number of nonzeros in Lagrangian Hessian.............:       22

Total number of variables............................:      316
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        0
                     variables with only upper bounds:        0
Total number of equality constraints.................:      112
Total number of inequality constraints...............:      294
        inequality constraints with only lower bounds:      294
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  

:Optimal

In [14]:
getValue(linkFlow)

22-element Array{Float64,1}:
  1800.0
  2700.0
  1800.0
  3700.0
  2700.0
  3800.0
  3800.0
  7200.0
  7200.0
  5300.0
  7900.0
  3700.0
  5300.0
  5200.0
  5300.0
  5200.0
  5300.0
  4900.0
  7900.0
  4900.0
 11500.0
 11500.0

In [15]:
getObjectiveValue(m)

487929.7719527845

In [16]:
using JuMP
using Gurobi

# m = Model(solver=GurobiSolver(OutputFlag=false))
m = Model()

numNodes = 10  # number of nodes

@defVar(m, linkFlow[1:numLinks])

@defVar(m, odLinkFlow[keys(demands), 1:numLinks])
for (s,t) = keys(demands)
    for k = 1:numLinks
        @addConstraint(m, odLinkFlow[(s,t), k] >= 0)
    end
end

for k = 1:numLinks
    linkFlowPartial = sum([odLinkFlow[(s,t), k] for (s,t) = keys(demands)])
    @addConstraint(m, linkFlowPartial == linkFlow[k])
end

for l = 1:numNodes
    for (s,t) = keys(demands)
        if s != t
            odLinkFlowPartial = sum([nodeLink["$(l-1)-$(k-1)"] * odLinkFlow[(s,t), k] for k = 1:numLinks])
            if (l == s)
                @addConstraint(m, odLinkFlowPartial + demands[(s,t)] == 0)
            elseif (l == t)
                @addConstraint(m, odLinkFlowPartial - demands[(s,t)] == 0)
            else
                @addConstraint(m, odLinkFlowPartial == 0)
            end
        end
    end
end

@defNLExpr(f, sum{free_flow_time[a]*linkFlow[a] + .03*free_flow_time[a]*((linkFlow[a])^5)/((capacity[a])^4), a = 1:numLinks})

@setNLObjective(m, Min, f)

solve(m)

This is Ipopt version 3.12.1, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

Number of nonzeros in equality constraint Jacobian...:     6182
Number of nonzeros in inequality constraint Jacobian.:     2200
Number of nonzeros in Lagrangian Hessian.............:       22

Total number of variables............................:     2222
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        0
                     variables with only upper bounds:        0
Total number of equality constraints.................:      922
Total number of inequality constraints...............:     2200
        inequality constraints with only lower bounds:     2200
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  

:Optimal

In [17]:
getValue(linkFlow)

22-element Array{Float64,1}:
  1800.0
  2700.0
  1800.0
  3700.0
  2700.0
  3800.0
  3800.0
  7200.0
  7200.0
  5300.0
  7900.0
  3700.0
  5300.0
  5200.0
  5300.0
  5200.0
  5300.0
  4900.0
  7900.0
  4900.0
 11500.0
 11500.0

In [18]:
getObjectiveValue(m)

487929.77188595134

In [ ]:
 1800.0
  2700.0
  1800.0
  3700.0
  2700.0
  3800.0
  3800.0
  7200.0
  7200.0
  5300.0
  7900.0
  3700.0
  5300.0
  5200.0
  5300.0
  5200.0
  5300.0
  4900.0
  7900.0
  4900.0
 11500.0
 11500.0

487929.7719527845