In [1]:
using PyCall
unshift!(PyVector(pyimport("sys")["path"]), "");
@pyimport Compute_Jacobian_MA_journal
@pyimport GLS_Apr_weekday_PM_journal

 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in transpose(::Ptr{PyCall.PyObject_struct}) at ./deprecated.jl:770
 in transpose_f!(::Base.#transpose, ::Array{Ptr{PyCall.PyObject_struct},2}, ::Array{Ptr{PyCall.PyObject_struct},2}) at ./arraymath.jl:369
 in transpose(::Array{Ptr{PyCall.PyObject_struct},2}) at ./arraymath.jl:407
 in copy(::PyCall.PyArray{Ptr{PyCall.PyObject_struct},2}) at /home/jzh/.julia/v0.5/PyCall/src/numpy.jl:337
 in convert(::Type{Array{Ptr{PyCall.PyObject_struct},N}}, ::PyCall.PyObject) at /home/jzh/.julia/v0.5/PyCall/src/numpy.jl:453
 in convert(::Type{Array{PyCall.PyObject,N}}, ::PyCall.PyObject) at /home/jzh/.julia/v0.5/PyCall/src/numpy.jl:484
 in convert(::Type{PyCall.PyAny}, ::PyCall.PyObject) at /home/jzh/.julia/v0.5/PyCall/src/conversions.jl:806
 in #55 at ./<missing>:0 [inlined]
 in next at ./generator.jl:26 [inlined]
 in collect_to!(::Array{Expr,1}, ::Base.Generator{Array{Tuple{AbstractString,PyCall.PyObject},1},PyCall.##55#59}, ::Int64, ::Int64) at

In [2]:
numNodes = Compute_Jacobian_MA_journal.numNodes;
numLinks = Compute_Jacobian_MA_journal.numLinks;
numODpairs = Compute_Jacobian_MA_journal.numODpairs;
numZones = Compute_Jacobian_MA_journal.numZones
od_pairs = Compute_Jacobian_MA_journal.od_pairs;
link_list_js = Compute_Jacobian_MA_journal.link_list_js;
link_length_list = Compute_Jacobian_MA_journal.link_length_list;

flow_observ = GLS_Apr_weekday_PM_journal.x_

258×30 Array{Float64,2}:
 1393.18     806.378    762.959        …  1122.05    1513.32     356.411 
 1245.77    1047.31    1023.88            1058.72    1286.13     737.719 
 2175.98    1580.96    1289.54            1310.68    1660.56    1011.89  
 2206.51    1358.68    1100.85            1375.95    2022.21     856.967 
   27.0447   279.236    279.358            114.702    182.177    319.842 
  143.919    260.583    207.122        …   112.767     47.7074    93.4537
  128.953     91.0833    77.1364           105.58     127.956     72.177 
  128.953     91.0833    77.1364           105.58     127.956     72.177 
 1381.89    1661.69    1435.11            1024.77    1282.9     1395.51  
 1061.96    1922.71    1849.59             893.572    782.416   2032.03  
   85.5516   284.675    357.062        …    50.566     29.8585   369.656 
  258.077    264.587    203.507            118.433    303.162    114.442 
  322.493    399.126    250.17             333.773    473.913    174.446 
    ⋮        

In [3]:
include("../Julia_files/initia_data.jl");
include("prepare_data_MA_journal.jl");
include("extract_data_MA_journal.jl");
include("../Julia_files/tap_MSA.jl");

 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in readall(::String, ::Vararg{String,N}) at ./deprecated.jl:30
 in furInfo() at /home/jzh/Research/Traffic/InverseVIsTraffic/08_develop_new_OD_demand_estimator_MA_Dijkstra_uni_class_Apr_PM_journal/prepare_data_MA_journal.jl:183
 in include_from_node1(::String) at ./loading.jl:488
 in include_string(::String, ::String) at ./loading.jl:441
 in execute_request(::ZMQ.Socket, ::IJulia.Msg) at /home/jzh/.julia/v0.5/IJulia/src/execute_request.jl:169
 in eventloop(::ZMQ.Socket) at /home/jzh/.julia/v0.5/IJulia/src/eventloop.jl:8
 in (::IJulia.##9#15)() at ./task.jl:360
while loading /home/jzh/Research/Traffic/InverseVIsTraffic/08_develop_new_OD_demand_estimator_MA_Dijkstra_uni_class_Apr_PM_journal/extract_data_MA_journal.jl, in expression starting on line 10
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in readall(::String, ::Vararg{String,N}) at ./deprecated.jl:30
 in furInfo() at /home/jzh/Research/Traffic/InverseVIsTraffic/08_de

In [4]:
deg = 8
c = 0.5
lam = 10000.0

coeffs_dict_Apr_PM_ = readstring("../temp_files/coeffs_dict_Apr_PM.json")
coeffs_dict_Apr_PM_ = JSON.parse(coeffs_dict_Apr_PM_)
fcoeffs = coeffs_dict_Apr_PM_["($(deg),$(c),$(lam),1)"]

9-element Array{Any,1}:
  1.0       
 -0.00303133
  0.0577207 
 -0.195677  
  0.620789  
 -0.905919  
  0.935921  
 -0.469131  
  0.108528  

In [5]:
day = 2

demandsDict = readstring("../08_develop_new_OD_demand_estimator_MA_Dijkstra_uni_class_Apr_PM_journal/results/demandsDictFixed$(day)_journal.json");
demandsDict = JSON.parse(demandsDict)

Dict{String,Any} with 5476 entries:
  "(62,58)" => 13.9269
  "(57,56)" => 0.00152636
  "(29,30)" => 8.26326
  "(69,26)" => 0.0
  "(37,58)" => 0.0
  "(45,24)" => 0.0
  "(41,72)" => 4.66273
  "(50,33)" => 0.0
  "(17,23)" => 0.0987195
  "(11,7)"  => 0.0
  "(67,15)" => 0.0
  "(28,45)" => 0.0
  "(55,28)" => 0.0
  "(66,63)" => 0.0
  "(48,58)" => 0.0
  "(14,32)" => 10.7954
  "(27,14)" => 0.0688458
  "(59,35)" => 13.7493
  "(50,72)" => 0.0
  "(55,40)" => 0.0
  "(44,28)" => 0.0
  "(2,30)"  => 0.0
  "(34,17)" => 0.0
  "(68,22)" => 5.15111
  "(59,38)" => 0.0
  ⋮         => ⋮

In [6]:
demandsDict_ = Dict()
for key in keys(demandsDict)
    key_ = (parse(Int, split(split(key, ',')[1], '(')[2]), parse(Int, split(split(key, ',')[2], ')')[1]))
    demandsDict_[key_] = demandsDict[key]
end

In [7]:
demandsDict_

Dict{Any,Any} with 5476 entries:
  (59,54) => 32.361
  (58,9)  => 0.0
  (21,13) => 31.2095
  (64,20) => 5.34183
  (53,24) => 0.0
  (65,20) => 5.34031
  (56,55) => 0.0
  (32,65) => 12.5782
  (41,34) => 0.0
  (62,58) => 13.9269
  (16,73) => 0.0114563
  (16,67) => 0.0
  (57,62) => 20.9636
  (57,74) => 0.0
  (63,12) => 0.0
  (24,31) => 0.0
  (1,22)  => 31.7149
  (6,41)  => 30.7671
  (37,55) => 0.0
  (61,48) => 0.0
  (60,46) => 0.0
  (19,26) => 0.0
  (68,4)  => 0.0
  (50,27) => 0.0
  (36,25) => 0.0
  ⋮       => ⋮

In [8]:
tapFlowDicDict = Dict()
tapFlowVecDict = Dict()
tapFlowDicDict[day], tapFlowVecDict[day] = tapMSA(demandsDict_, fcoeffs);

In [9]:
tapFlowVecDict[day]

258-element Array{Float64,1}:
  716.607     
  405.89      
 2148.33      
 1531.49      
    0.0       
    0.0       
 1830.86      
 1981.31      
 2261.46      
 3727.38      
    0.410871  
    0.00619807
    0.0       
    ⋮         
  288.512     
  660.443     
  660.513     
  288.58      
 3108.88      
 1800.78      
  813.404     
  976.97      
 3112.72      
 1806.66      
 1228.17      
 1623.76      

In [10]:
tapSocialFlowDicDict = Dict()
tapSocialFlowVecDict = Dict()
tapSocialFlowDicDict[day], tapSocialFlowVecDict[day] = tapMSASocial(demandsDict_, fcoeffs);

In [11]:
tapSocialFlowVecDict[day]

258-element Array{Float64,1}:
  716.607     
  405.89      
 2148.33      
 1531.49      
    0.0       
    0.0       
 1830.86      
 1981.31      
 2261.46      
 3727.38      
    0.410871  
    0.00619807
    0.0       
    ⋮         
  288.512     
  660.443     
  660.513     
  288.58      
 3108.88      
 1800.78      
  813.404     
  976.97      
 3112.72      
 1806.66      
 1228.17      
 1623.76      

In [12]:
flow_observ[:, day]

258-element Array{Float64,1}:
  806.378 
 1047.31  
 1580.96  
 1358.68  
  279.236 
  260.583 
   91.0833
   91.0833
 1661.69  
 1922.71  
  284.675 
  264.587 
  399.126 
    ⋮     
  361.35  
  361.35  
  444.253 
  444.253 
  281.248 
  281.248 
  197.688 
  343.812 
  618.474 
  618.474 
   88.6479
  376.191 

In [13]:
function socialObj(linkFlowVec)
    objVal = sum([free_flow_time[a] * fcoeffs[1] * linkFlowVec[a] + 
        free_flow_time[a] * fcoeffs[2] * linkFlowVec[a]^2 / capacity[a] + 
        free_flow_time[a] * fcoeffs[3] * linkFlowVec[a]^3 / capacity[a]^2 + 
        free_flow_time[a] * fcoeffs[4] * linkFlowVec[a]^4 / capacity[a]^3 + 
        free_flow_time[a] * fcoeffs[5] * linkFlowVec[a]^5 / capacity[a]^4 + 
        free_flow_time[a] * fcoeffs[6] * linkFlowVec[a]^6 / capacity[a]^5 + 
        free_flow_time[a] * fcoeffs[7] * linkFlowVec[a]^7 / capacity[a]^6 + 
        free_flow_time[a] * fcoeffs[8] * linkFlowVec[a]^8 / capacity[a]^7 + 
        free_flow_time[a] * fcoeffs[9] * linkFlowVec[a]^9 / capacity[a]^8 for a = 1:numLinks])
    return objVal
end

socialObj (generic function with 1 method)

In [14]:
PoA_dict = Dict()

PoA_dict[day] = socialObj(tapFlowVecDict[day]) / socialObj(tapSocialFlowVecDict[day])

1.0

In [15]:
PoA_dict = Dict()

PoA_dict[day] = socialObj(flow_observ[:, day]) / socialObj(tapSocialFlowVecDict[day])

0.7423602957544482