In [1]:
# based on https://github.com/chkwon/TrafficAssignment.jl

In [2]:
include("../Julia_files/load_network_uni-class.jl")

load_ta_network (generic function with 2 methods)

In [3]:
using Graphs

function create_graph(start_node, end_node)
    @assert length(start_node)==length(end_node)

    no_node = max(maximum(start_node), maximum(end_node))
    no_arc = length(start_node)

    graph = simple_inclist(no_node)
    for i=1:no_arc
        add_edge!(graph, start_node[i], end_node[i])
    end
    return graph
end

create_graph (generic function with 1 method)

In [4]:
function get_vector(state, origin, destination, link_dic)
    current = destination
    parent = -1
    x = zeros(Int, maximum(link_dic))

    while parent != origin
        parent = state.parents[current]

        link_idx = link_dic[parent,current]

        if link_idx != 0
            x[link_idx] = 1
        end

        current = parent
    end

    return x
end

get_vector (generic function with 1 method)

In [5]:
ta_data = load_ta_network("Sioux Falls")

TA_Data("Sioux Falls",24,24,1,76,[1,1,2,2,3,3,3,4,4,4  …  22,22,22,22,23,23,23,24,24,24],[2,3,1,6,1,4,12,3,5,11  …  15,20,21,23,14,22,24,13,21,23],[25900.2,23403.5,25900.2,4958.18,23403.5,17110.5,23403.5,17110.5,17782.8,4908.83  …  9599.18,5075.7,5229.91,5000.0,4924.79,5000.0,5078.51,5091.26,4885.36,5078.51],[6.0,4.0,6.0,5.0,4.0,4.0,4.0,4.0,2.0,6.0  …  3.0,5.0,2.0,4.0,4.0,4.0,2.0,4.0,3.0,2.0],[6.0,4.0,6.0,5.0,4.0,4.0,4.0,4.0,2.0,6.0  …  3.0,5.0,2.0,4.0,4.0,4.0,2.0,4.0,3.0,2.0],[0.15,0.15,0.15,0.15,0.15,0.15,0.15,0.15,0.15,0.15  …  0.15,0.15,0.15,0.15,0.15,0.15,0.15,0.15,0.15,0.15],[4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0  …  4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0],[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0  …  0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0  …  0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[1,1,1,1,1,1,1,1,1,1  …  1,1,1,1,1,1,1,1,1,1],360600.0,24x24 Array{Float64,2}:
    0.0  100.0  100.0   500.0   200.0  …   100.0   400.0   300.0   100.0
  

In [6]:
ta_data.od_pairs

576-element Array{(Int64,Int64),1}:
 (1,1)  
 (1,2)  
 (1,3)  
 (1,4)  
 (1,5)  
 (1,6)  
 (1,7)  
 (1,8)  
 (1,9)  
 (1,10) 
 (1,11) 
 (1,12) 
 (1,13) 
 ⋮      
 (24,13)
 (24,14)
 (24,15)
 (24,16)
 (24,17)
 (24,18)
 (24,19)
 (24,20)
 (24,21)
 (24,22)
 (24,23)
 (24,24)

In [7]:
# unpacking data from ta_data
network_name = ta_data.network_name

number_of_zones = ta_data.number_of_zones
number_of_nodes = ta_data.number_of_nodes
first_thru_node = ta_data.first_thru_node
number_of_links = ta_data.number_of_links

start_node = ta_data.start_node
end_node = ta_data.end_node
capacity = ta_data.capacity
link_length = ta_data.link_length

free_flow_time = ta_data.free_flow_time
B = ta_data.B
power = ta_data.power
speed_limit = ta_data.speed_limit
toll = ta_data.toll
link_type = ta_data.link_type
number_of_zones = ta_data.number_of_zones
total_od_flow = ta_data.total_od_flow
travel_demand = ta_data.travel_demand
od_pairs = ta_data.od_pairs

toll_factor = ta_data.toll_factor
distance_factor = ta_data.distance_factor

best_objective = ta_data.best_objective

0.0

In [8]:
# dividing the travel_demand into two classes (car and truck)
travel_demand_car = travel_demand * .8
travel_demand_truck = travel_demand * .2

assert(travel_demand_car + travel_demand_truck == travel_demand)

In [9]:
# preparing a graph
graph = create_graph(start_node, end_node)
link_dic = sparse(start_node, end_node, 1:number_of_links)

24x24 sparse matrix with 76 Int64 entries:
	[2 ,  1]  =  3
	[3 ,  1]  =  5
	[1 ,  2]  =  1
	[6 ,  2]  =  14
	[1 ,  3]  =  2
	[4 ,  3]  =  8
	[12,  3]  =  35
	[3 ,  4]  =  6
	[5 ,  4]  =  11
	[11,  4]  =  31
	⋮
	[24, 21]  =  75
	[15, 22]  =  46
	[20, 22]  =  63
	[21, 22]  =  65
	[23, 22]  =  72
	[14, 23]  =  42
	[22, 23]  =  70
	[24, 23]  =  76
	[13, 24]  =  39
	[21, 24]  =  66
	[23, 24]  =  73

In [10]:
graph.vertices

1:24

In [11]:
function BPR(x)
    # travel_time = free_flow_time .* ( 1.0 + B .* (x./capacity).^power )
    # generalized_cost = travel_time + toll_factor *toll + distance_factor * link_length
    # return generalized_cost

    bpr = similar(x)
    for i=1:length(bpr)
        bpr[i] = free_flow_time[i] * ( 1.0 + B[i] * (x[i]/capacity[i])^power[i] )
    end
    return bpr
end

BPR (generic function with 1 method)

In [12]:
function all_or_nothing(travel_time)
    state = []
    path = []
    x = zeros(size(start_node))

    for r=1:size(travel_demand)[1]
        # for each origin node r, find shortest paths to all destination nodes
        state = dijkstra_shortest_paths(graph, travel_time, r)

        for s=1:size(travel_demand)[2]
            # for each destination node s, find the shortest-path vector
            # load travel demand
            x = x + travel_demand[r,s] * get_vector(state, r, s, link_dic)
        end
    end

    return x
end

all_or_nothing (generic function with 1 method)

In [13]:
function all_or_nothing_car(travel_time_car)
    state = []
    path = []
    x = zeros(size(start_node))

    for r=1:size(travel_demand_car)[1]
        # for each origin node r, find shortest paths to all destination nodes
        state = dijkstra_shortest_paths(graph, travel_time_car, r)

        for s=1:size(travel_demand_car)[2]
            # for each destination node s, find the shortest-path vector
            # load travel demand
            x = x + travel_demand_car[r,s] * get_vector(state, r, s, link_dic)
        end
    end

    return x
end

all_or_nothing_car (generic function with 1 method)

In [14]:
function all_or_nothing_truck(travel_time_truck)
    state = []
    path = []
    x = zeros(size(start_node))

    for r=1:size(travel_demand_truck)[1]
        # for each origin node r, find shortest paths to all destination nodes
        state = dijkstra_shortest_paths(graph, travel_time_truck, r)

        for s=1:size(travel_demand_truck)[2]
            # for each destination node s, find the shortest-path vector
            # load travel demand
            x = x + travel_demand_truck[r,s] * get_vector(state, r, s, link_dic)
        end
    end

    return x
end

all_or_nothing_truck (generic function with 1 method)

In [15]:
# Finding a starting feasible solution
travel_time = BPR(zeros(number_of_links));
xl = all_or_nothing(travel_time);

travel_time_car = 1.0 * BPR(zeros(number_of_links));
travel_time_truck = 1.1 * BPR(zeros(number_of_links));
#travel_time_truck = 1.0 * BPR(zeros(number_of_links));

xl_car = all_or_nothing_car(travel_time_car);
xl_truck = all_or_nothing_truck(travel_time_truck);

In [16]:
max_iter_no = 1e3
l = 1
#average_excess_cost = 1
tol = 1e-5

while l < max_iter_no
    l += 1
    
    ## Finding yl
    #travel_time = BPR(xl)
    #yl = all_or_nothing(travel_time)
    #xl = xl + (yl - xl)/l
    
    # Finding yl_car
    xl_car_old = xl_car
    travel_time_car = 1.0 * BPR(xl_car + 2.0 * xl_truck)
    yl_car = all_or_nothing_car(travel_time_car)
    xl_car = xl_car + (yl_car - xl_car)/l
    xl_car_new = xl_car
    
    # Finding yl_truck
    xl_truck_old = xl_truck
    travel_time_truck = 1.1 * BPR(xl_car + 2.0 * xl_truck)
    yl_truck = all_or_nothing_truck(travel_time_truck)
    xl_truck = xl_truck + (yl_truck - xl_truck)/l
    xl_truck_new = xl_truck
    
    
    relative_gap_car = norm(xl_car_new - xl_car_old, 1) / norm(xl_car_new, 1)
    relative_gap_truck = norm(xl_truck_new - xl_truck_old, 1) / norm(xl_truck_new, 1)
    
    if l % 10000 == 0
        print("l = $l------------------------------------------------\n")
        print("relative_gap_car is $relative_gap_car\n")
        print("relative_gap_truck is $relative_gap_truck\n")
    end

    if relative_gap_car < tol && relative_gap_truck < tol
        print("l = $l------------------------------------------------\n")
        print("relative_gap_car is $relative_gap_car\n")
        print("relative_gap_truck is $relative_gap_truck\n")
        break
    end
    
end

In [17]:
outfile = open("../data_original/flows_car_converge_1e-5.txt", "w")

write(outfile, join(("From", "to", "Volume_Capacity"), "        "), "\n")

for i = 1:length(ta_data.start_node)
     n1, n2, n3 = ta_data.start_node[i], ta_data.end_node[i], xl_car[i]
     write(outfile, join((n1, n2, n3), "        "), "\n")
end

close(outfile)

In [18]:
outfile = open("../data_original/flows_truck_converge_1e-5.txt", "w")

write(outfile, join(("From", "to", "Volume_Capacity"), "        "), "\n")

for i = 1:length(ta_data.start_node)
     n1, n2, n3 = ta_data.start_node[i], ta_data.end_node[i], xl_truck[i]
     write(outfile, join((n1, n2, n3), "        "), "\n")
end

close(outfile)

In [19]:
tapFlows = Dict{}()
tapFlowsCar = Dict{(Int64,Int64),Float64}()
tapFlowsTruck = Dict{(Int64,Int64),Float64}()
tapFlowVect = zeros(2,length(xl_car))

for i = 1:length(ta_data.start_node)
    key = (ta_data.start_node[i], ta_data.end_node[i])
    tapFlowsCar[key] = xl_car[i]
    tapFlowsTruck[key] = xl_truck[i]
end
tapFlows[1] = tapFlowsCar
tapFlows[2] = tapFlowsTruck

for j = 1:length(xl_car)
    tapFlowVect[1,j] = xl_car[j]
    tapFlowVect[2,j] = xl_truck[j]
end

In [20]:
tapFlowVect

2x76 Array{Float64,2}:
 4967.28  7874.96  4993.52  4801.6   …  5775.28  8412.64  8266.0   5744.48
 1169.66  1893.72  1173.44  1128.44     1709.74  2117.6   1822.12  1695.02

In [21]:
tapFlows

Dict{Any,Any} with 2 entries:
  2 => [(15,19)=>3813.999999999998,(20,21)=>1260.9200000000012,(22,20)=>1396.63…
  1 => [(15,19)=>14759.920000000011,(20,21)=>5083.680000000003,(22,20)=>5622.63…

In [22]:
xl_car

76-element Array{Float64,1}:
  4967.28
  7874.96
  4993.52
  4801.6 
  7848.72
 12657.8 
  9536.64
 12703.4 
 15148.6 
  4018.8 
 15304.6 
  5929.36
 12982.2 
     ⋮   
  6779.92
  8319.44
 13803.3 
  5622.64
  6767.52
  7400.96
  6074.16
  7425.68
  5775.28
  8412.64
  8266.0 
  5744.48

In [23]:
xl_truck

76-element Array{Float64,1}:
 1169.66
 1893.72
 1173.44
 1128.44
 1889.94
 3592.3 
 2687.18
 3550.78
 3946.18
 1294.64
 3907.02
 1469.06
 3417.2 
    ⋮   
 1458.1 
 1827.88
 3314.92
 1396.64
 1460.04
 1941.02
 1702.92
 1907.02
 1709.74
 2117.6 
 1822.12
 1695.02