In [1]:
using JSON

#load OD pair-route incidence
odPairRoute = readall("od_pair_route_incidence_MA.json");
odPairRoute = JSON.parse(odPairRoute);

#load link-route incidence
linkRoute = readall("link_route_incidence_MA.json");
linkRoute = JSON.parse(linkRoute);

#load OD pair labels
odPairLabel = readall("od_pair_label_dict_MA_refined.json");
odPairLabel = JSON.parse(odPairLabel);

odPairLabel_ = readall("od_pair_label_dict__MA_refined.json");
odPairLabel_ = JSON.parse(odPairLabel_);

#load link labels
linkLabel = readall("link_label_dict_MA.json");
linkLabel = JSON.parse(linkLabel);

linkLabel_ = readall("link_label_dict_MA_.json");
linkLabel_ = JSON.parse(linkLabel_);

#load node-link incidence
nodeLink = readall("node_link_incidence_MA.json");
nodeLink = JSON.parse(nodeLink);

In [2]:
include("load_network_uni-class.jl")

load_ta_network (generic function with 2 methods)

In [3]:
ta_data = load_ta_network("East_Massachusetts_Jan_PM");

In [4]:
capacity = ta_data.capacity;
free_flow_time = ta_data.free_flow_time;

In [5]:
############
#Read in the demand file
file = open("East_Massachusetts_trips_Jan_PM.txt")
demands = Dict{(Int64,Int64), Float64}()
s = 0
for line in eachline(file)
    if contains(line, "Origin")
        s = int(split(line)[2])
    else
        pairs = split(line, ";")
        for pair in pairs
            if !contains(pair, "\n")
                pair_vals = split(pair, ":")
                t, demand = int(pair_vals[1]), float(pair_vals[2])
                demands[(s,t)] = demand 
            end
        end
    end
end                
close(file)

In [6]:
demands

Dict{(Int64,Int64),Float64} with 64 entries:
  (3,6) => 3000.0
  (4,4) => 0.0
  (3,1) => 1000.0
  (4,5) => 5000.0
  (2,4) => 2000.0
  (6,5) => 2000.0
  (8,4) => 7000.0
  (1,2) => 1000.0
  (5,1) => 2000.0
  (3,4) => 2000.0
  (8,2) => 4000.0
  (2,3) => 1000.0
  (2,6) => 4000.0
  (5,4) => 5000.0
  (2,1) => 1000.0
  (2,5) => 1000.0
  (8,5) => 5000.0
  (1,4) => 5000.0
  (2,8) => 4000.0
  (5,8) => 5000.0
  (4,8) => 7000.0
  (7,8) => 10000.0
  (1,1) => 0.0
  (7,7) => 0.0
  (5,7) => 2000.0
  ⋮     => ⋮

In [7]:
odPairLabel_

Dict{String,Any} with 56 entries:
  "32" => {5,4}
  "29" => {5,1}
  "1"  => {1,2}
  "54" => {8,5}
  "2"  => {1,3}
  "41" => {6,7}
  "53" => {8,4}
  "51" => {8,2}
  "27" => {4,7}
  "42" => {6,8}
  "33" => {5,6}
  "28" => {4,8}
  "52" => {8,3}
  "50" => {8,1}
  "26" => {4,6}
  "10" => {2,4}
  "24" => {4,3}
  "25" => {4,5}
  "23" => {4,2}
  "49" => {7,8}
  "5"  => {1,6}
  "31" => {5,3}
  "43" => {7,1}
  "39" => {6,4}
  "44" => {7,2}
  ⋮    => ⋮

In [8]:
demandsVec = zeros(56)

for i = 1:length(demandsVec)
    demandsVec[i] = demands[(odPairLabel_["$i"][1], odPairLabel_["$i"][2])]
end

In [9]:
demandsVec

56-element Array{Float64,1}:
  1000.0
  1000.0
  5000.0
  2000.0
  3000.0
  5000.0
  8000.0
  1000.0
  1000.0
  2000.0
  1000.0
  4000.0
  2000.0
     ⋮  
  1000.0
  4000.0
  2000.0
  4000.0
 10000.0
  8000.0
  4000.0
  2000.0
  7000.0
  5000.0
  8000.0
 10000.0

In [10]:
for key=keys(odPairRoute)
    if contains(key, "56-")
        println(key)
    end
end

56-724
56-721
56-719
56-717
56-718
56-715
56-722
56-723
56-713
56-714
56-720
56-716


In [11]:
using JuMP

# m = Model(solver=GurobiSolver(OutputFlag=false))
m = Model()

numLinks = 24
numRoute = 724
numOD = 56

@defVar(m, linkFlow[1:numLinks])
@defVar(m, pathFlow[1:numRoute])

pathFlowSum = Dict()

for i=1:numOD
    pathFlowSum[i] = 0
    for j=1:numRoute
        if "$(i)-$(j)" in keys(odPairRoute)
            pathFlowSum[i] += pathFlow[j]
        end
    end
    @addConstraint(m, pathFlowSum[i] == demandsVec[i])
end

pathFlowLinkSum = Dict()

for a=1:numLinks
    pathFlowLinkSum[a] = 0
    for j=1:numRoute
        if "$(a)-$(j)" in keys(linkRoute)
            pathFlowLinkSum[a] += pathFlow[j]
        end
    end
    @addConstraint(m, pathFlowLinkSum[a] == linkFlow[a])
end

for j=1:numRoute
    @addConstraint(m, pathFlow[j] >= 0)
end

@defNLExpr(f, sum{free_flow_time[a]*linkFlow[a] + .03*free_flow_time[a]*((linkFlow[a])^5)/((capacity[a])^4), a = 1:numLinks})

@setNLObjective(m, Min, f)

solve(m)


******************************************************************************
This program contains Ipopt, a library for large-scale nonlinear optimization.
 Ipopt is released as open source code under the Eclipse Public License (EPL).
         For more information visit http://projects.coin-or.org/Ipopt
******************************************************************************

This is Ipopt version 3.12.1, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

Number of nonzeros in equality constraint Jacobian...:     4092
Number of nonzeros in inequality constraint Jacobian.:      724
Number of nonzeros in Lagrangian Hessian.............:       24

Total number of variables............................:      748
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        0
                     variables with only upper bounds:        0
Total number of equa

:Optimal

In [12]:
getValue(linkFlow)

24-element Array{Float64,1}:
 12449.5
 12098.2
 12550.5
 12901.8
  8000.0
  8000.0
 17449.5
 17098.2
 14969.6
 15529.0
 12581.0
 12372.8
 15398.7
 15000.0
  6000.0
  6000.0
 17449.5
 17496.9
 19969.6
 20130.3
 14581.0
 14372.8
 26550.5
 26503.1

In [13]:
getObjectiveValue(m)

105939.14129007379

In [14]:
flows = Dict{(Int64,Int64),Float64}()

for i = 1:length(ta_data.start_node)
    key = (ta_data.start_node[i], ta_data.end_node[i])
    flows[key] = getValue(linkFlow)[i]
end

flows

Dict{(Int64,Int64),Float64} with 24 entries:
  (3,6) => 12580.962934857382
  (2,3) => 8000.000006211795
  (5,6) => 5999.999999657815
  (5,4) => 15000.000045688375
  (2,1) => 12098.207517230503
  (6,3) => 12372.81605908074
  (3,1) => 12901.792481501747
  (1,3) => 12550.538550238449
  (4,5) => 15398.718801194647
  (4,8) => 17449.461488020588
  (7,5) => 20130.257621172972
  (8,7) => 26503.073680127836
  (3,2) => 8000.000000309591
  (7,6) => 14372.81605870905
  (2,4) => 17449.461441646225
  (7,8) => 26550.538510273043
  (6,5) => 5999.999999680477
  (6,7) => 14580.962934463025
  (8,4) => 17496.92631816578
  (1,2) => 12449.461448493807
  (5,3) => 15528.976422823958
  (4,2) => 17098.207516285114
  (3,5) => 14969.575621686221
  (5,7) => 19969.575575564166

In [15]:
outfile = open("flows_MA.json", "w")

JSON.print(outfile, flows)

close(outfile)

In [16]:
using JuMP

# m = Model(solver=GurobiSolver(OutputFlag=false))
m = Model()

numLinks = 24  # number of links
numNodes = 8  # number of nodes

@defVar(m, linkFlow[1:numLinks])

@defVar(m, odLinkFlow[keys(demands), 1:numLinks])
for (s,t) = keys(demands)
    for k = 1:numLinks
        @addConstraint(m, odLinkFlow[(s,t), k] >= 0)
    end
end

for k = 1:numLinks
    linkFlowPartial = sum([odLinkFlow[(s,t), k] for (s,t) = keys(demands)])
    @addConstraint(m, linkFlowPartial == linkFlow[k])
end

for l = 1:numNodes
    for (s,t) = keys(demands)
        if s != t
            odLinkFlowPartial = sum([nodeLink["$(l-1)-$(k-1)"] * odLinkFlow[(s,t), k] for k = 1:numLinks])
            if (l == s)
                @addConstraint(m, odLinkFlowPartial + demands[(s,t)] == 0)
            elseif (l == t)
                @addConstraint(m, odLinkFlowPartial - demands[(s,t)] == 0)
            else
                @addConstraint(m, odLinkFlowPartial == 0)
            end
        end
    end
end

@defNLExpr(f, sum{free_flow_time[a]*linkFlow[a] + .03*free_flow_time[a]*((linkFlow[a])^5)/((capacity[a])^4), a = 1:24})

@setNLObjective(m, Min, f)

solve(m)

This is Ipopt version 3.12.1, running with linear solver mumps.
NOTE: Other linear solvers might be more efficient (see Ipopt documentation).

Number of nonzeros in equality constraint Jacobian...:     4248
Number of nonzeros in inequality constraint Jacobian.:     1536
Number of nonzeros in Lagrangian Hessian.............:       24

Total number of variables............................:     1560
                     variables with only lower bounds:        0
                variables with lower and upper bounds:        0
                     variables with only upper bounds:        0
Total number of equality constraints.................:      472
Total number of inequality constraints...............:     1536
        inequality constraints with only lower bounds:     1536
   inequality constraints with lower and upper bounds:        0
        inequality constraints with only upper bounds:        0

iter    objective    inf_pr   inf_du lg(mu)  ||d||  lg(rg) alpha_du alpha_pr  ls
   0  

:Optimal

In [17]:
getValue(linkFlow)

24-element Array{Float64,1}:
 12449.5
 12098.2
 12550.5
 12901.8
  8000.0
  8000.0
 17449.5
 17098.2
 14969.6
 15529.0
 12581.0
 12372.8
 15398.7
 15000.0
  6000.0
  6000.0
 17449.5
 17496.9
 19969.6
 20130.3
 14581.0
 14372.8
 26550.5
 26503.1

In [18]:
getObjectiveValue(m)

105939.1412938222

In [19]:
outfile = open("flows_converge.txt", "w")

write(outfile, join(("From", "to", "Volume_Capacity"), "        "), "\n")

for i = 1:length(ta_data.start_node)
     n1, n2, n3 = ta_data.start_node[i], ta_data.end_node[i], getValue(linkFlow)[i]
     write(outfile, join((n1, n2, n3), "        "), "\n")
end

close(outfile)

In [20]:
capacity

24-element Array{Float64,1}:
 14699.6
 14306.7
 18114.8
 18355.2
 18827.2
 17196.2
 15365.5
 15354.3
 19942.7
 19596.0
 18921.6
 16388.7
 14387.5
 16011.2
 14815.3
 11905.0
 15000.0
 15000.0
 18095.9
 18215.6
 17324.1
 16728.5
 15000.0
 15000.0

In [21]:
flows

Dict{(Int64,Int64),Float64} with 24 entries:
  (3,6) => 12580.962934857382
  (2,3) => 8000.000006211795
  (5,6) => 5999.999999657815
  (5,4) => 15000.000045688375
  (2,1) => 12098.207517230503
  (6,3) => 12372.81605908074
  (3,1) => 12901.792481501747
  (1,3) => 12550.538550238449
  (4,5) => 15398.718801194647
  (4,8) => 17449.461488020588
  (7,5) => 20130.257621172972
  (8,7) => 26503.073680127836
  (3,2) => 8000.000000309591
  (7,6) => 14372.81605870905
  (2,4) => 17449.461441646225
  (7,8) => 26550.538510273043
  (6,5) => 5999.999999680477
  (6,7) => 14580.962934463025
  (8,4) => 17496.92631816578
  (1,2) => 12449.461448493807
  (5,3) => 15528.976422823958
  (4,2) => 17098.207516285114
  (3,5) => 14969.575621686221
  (5,7) => 19969.575575564166